DROP TABLE IF EXISTS players;

CREATE TABLE players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    day INTEGER NOT NULL DEFAULT 1,
    money INTEGER NOT NULL DEFAULT 50,
    english INTEGER NOT NULL DEFAULT 5,
    energy INTEGER NOT NULL DEFAULT 60,
    mood INTEGER NOT NULL DEFAULT 60,
    achievements TEXT NOT NULL DEFAULT '[]',
    log TEXT NOT NULL DEFAULT '[]',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

